// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lefwanepafolnbjxnhcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlZndhbmVwYWZvbG5ianhuaGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjE3MDQsImV4cCI6MjA2OTE5NzcwNH0._M87aK6O76XY6u3-rvLv5PrK7LfqA9bMUGP2XWQdOQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});